### PR TITLE
Update readme with details on Windows & WinRM support

### PR DESCRIPTION
**Pull request by matt-richardson**
Updates the ReadMe following the windows/winrm changes from https://github.com/Azure/vagrant-azure/pull/152.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matt-richardson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
@matt-richardson please resolve the conflicts.

**Comment by matt-richardson** [comment]
Resolved.

**Comment by devigned** [comment]
Thank you!

**Pull request merged**
