### PR TITLE
Support Windows & WinRM

### PR DESCRIPTION
**Pull request by matt-richardson**
This PR builds on top of the excellent work by @rysweet in #115, and finishes off the WinRM support.

Its still a work in progress, but the basics are working.

Things that are outstanding:
- [x] WinRM port hardcoded to 5986
- [x] WinRM transport is hardcoded to ssl
- [x] WinRM ssl peer verification is hardcoded to false
- [ ] The retrying message is not translated correctly
- [x] Template is hardcoded to install self-signed cert on port 5986 using files downloaded from github
- [ ] Config validation needs updating

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@matt-richardson__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@matt-richardson__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by matt-richardson** [comment]
@devigned - this is ready for review now. I'll continue to work on the other bits, but I think it's in a good enough state for a new pre-release to go.

**Comment by devigned** [comment]
LGTM! Thank you for the contribution.

**Comment by matt-richardson** [comment]
Thanks for merging.
I still need to update the readme to talk about the new options - I'll submit a new PR for that later today.

What's your thoughts/plans for a new (pre-)release?

**Comment by matt-richardson** [comment]
Just updating the readme (PR to follow shortly), and I've realised we've now got `vm_password` and `admin_password` as properties now. `vm_password` is not used.

Would you prefer:
* keep `admin_username` and `admin_password`, and delete `vm_password`?
* keep `vm_password` and rename `admin_username` to `vm_username` and delete `admin_password`?

**Comment by devigned** [comment]
@matt-richardson I'm going through a few updates to some of the underlying libraries, then I'll issue another pull request with those changes. After pulling in that, I'll publish a new preview release.

**Comment by matt-richardson** [comment]
Cool - let me know if you want me to test.

**Comment by devigned** [comment]
@matt-richardson will do. I'm hoping to get it pushed up in just a bit. I'll tag you on the PR.

**Pull request merged**
