### PR TITLE
Update to the latest version of the ruby sdk for Azure

### LINKED ISSUE #88: Better documentation for certification stuff and Azure
Unfortunately it not readable at all :(

Going to add some more explanation about providing certificates, because it's big pain right now.
[related problem](https://github.com/MSOpenTech/vagrant-azure/issues/25#issuecomment-114315592)

started my work [here](https://github.com/pawelsawicz/vagrant-azure/tree/update-readme-certificates)

### PR DESCRIPTION
**Pull request by devigned**
- update to the latest version of the ruby sdk for azure
-- includes updates to all the machine sizes available in azure
-- provides more consistent http client support
-- provides more options for specifying management certificates (pfx, pem, and raw strings)
- update docs with better documentation of ssh configuration and private key support
- update winrm support with the 1.3.3 winrm gem
- remove confusing certificate_file_path, which wasn't used

should fix #88, #86, #83, #77, #76, #75

### CODE REVIEW

**Comment by kshmir** [comment]
@devigned I am trying to run this but I get the following error... 

     Installing the 'vagrant-azure-1.1.1.gem' plugin. This can take a few minutes...
     The plugin(s) can't be installed due to the version conflicts below.
     This means that the plugins depend on a library version that conflicts
     with other plugins or Vagrant itself, creating an impossible situation
     where Vagrant wouldn't be able to load the plugins.

     You can fix the issue by either removing a conflicting plugin or
     by contacting a plugin author to see if they can address the conflict.

     Vagrant could not find compatible versions for gem "mime-types":
       In Gemfile:
         vagrant-azure (= 1.1.1) ruby depends on
           azure (= 0.7.0.pre2) ruby depends on
             mime-types (~> 2.0) ruby

         vagrant-share (>= 0) ruby depends on
           rest-client (~> 1.6.0) ruby depends on
             mime-types (~> 1.16) ruby

**Comment by kshmir** [comment]
I have vagrant 1.7.3 on ubuntu.

**Comment by kshmir** [comment]
@devigned can this be the source? https://github.com/Azure/azure-sdk-for-ruby/pull/242 Or maybe I have a problem with my vagrant!

**Comment by kshmir** [comment]
@devigned I forked and it seemed to work... the problem comes obviously from vagrant-share, but in the meantime changing azure's dependency to >= 1.0 should let bundler handle the problem for most of us. (Unless somebody uses vagrant-share and chef-client... in that case it'll break).

**Comment by devigned** [comment]
@kshmir this should be sorted out in Vagrant-Azure 1.2.0 which depends on Azure 0.7.0.

**Comment by kshmir** [comment]
Great thanks!

El lunes, 17 de agosto de 2015, David Justice <notifications@github.com>
escribió:

> @kshmir <https://github.com/kshmir> this should be sorted out in
> Vagrant-Azure 1.2.0 which depends on Azure 0.7.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MSOpenTech/vagrant-azure/pull/90#issuecomment-131731472>
> .
>


-- 
Cristian Pereyra

**Pull request merged**
