### PR TITLE
Update the project

### LINKED ISSUE #150: Plugin fails to install with vagrant 1.9.1
Installing the plugin fails on vagrant 1.9.1 with the following error:
```
$ vagrant --version
Vagrant 1.9.1
$ vagrant plugin install vagrant-azure
Installing the 'vagrant-azure' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.99.3, already activated mime-types-3.1 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:323:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:248:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:98:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

I need to use the service management version, rather than the azure resource manager version as I need classic VMs.

Rolling back to vagrant 1.8.7 works.

### PR DESCRIPTION
**Pull request by devigned**
- Update the Azure SDK libs to 0.8.0
- Update to use Premium storage for faster deployments
- Don't wait on destruction of the resource group, but just issue the delete call
- Update the VM to Standard_DS2_v2 by default
- Don't default to NFS, but rather fall back to rsync by default
- Default admin username and password, which was causing failures when spinning up a default linux box
- Remove boot diagnostics to simplify the storage dependency

resolves #150, #153, #149, #147

### CODE REVIEW

**Comment by devigned** [comment]
@matt-richardson, please give this a try when you have a sec.

**Comment by matt-richardson** [comment]
Looking...

**Comment by matt-richardson** [comment]
Falls over:

```
Bringing machine 'default' up with 'azure' provider...
==> default: Launching an instance with the following settings...
==> default:  -- Management Endpoint: https://management.azure.com
==> default:  -- Subscription Id: 1ad749f5-ce35-4ed1-9d6f-d6292ae0d62e
==> default:  -- Resource Group Name: TestAzureVmExt
==> default:  -- Location: AustraliaEast
==> default:  -- Admin Username: OctoAdmin
==> default:  -- VM Name: TestAzureVmExt
==> default:  -- VM Size: Standard_D2
==> default:  -- Image URN: MicrosoftSQLServer:SQL2016-WS2012R2:Express:latest
==> default:  -- DNS Label Prefix: throbbing-shape-42
/Users/mattr/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre1/lib/vagrant-azure/action/run_instance.rb:185:in `get_image_details': undefined method `sort_by' for #<Concurrent::Promise:0x00000102b61dd8> (NoMethodError)
	from /Users/mattr/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre1/lib/vagrant-azure/action/run_instance.rb:73:in `block in call'
	from /Users/mattr/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre1/lib/vagrant-azure/util/timer.rb:7:in `time'
	from /Users/mattr/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre1/lib/vagrant-azure/action/run_instance.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/mattr/.vagrant.d/gems/gems/vagrant-azure-2.0.0.pre1/lib/vagrant-azure/action/connect_azure.rb:23:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/mattr/.vagrant.d/gems/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/mattr/.vagrant.d/gems/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/mattr/.vagrant.d/gems/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:567:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	from /opt/vagrant/embedded/gems/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `call'
	from /opt/vagrant/embedded/gems/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
```

(ignore the odd path - I copied and pasted into the `2.0.0-pre1` folder)

**Comment by devigned** [comment]
@matt-richardson, hmm... did you run that with `bundle exec vagrant up --provider=azure`? I suspect you are using the 0.2.1 version of the Azure Ruby SDK.

**Comment by matt-richardson** [comment]
I didn't do the bundle exec approach, no... To be honest, no idea how to make it work. Running the `bundle exec ...` from the folder with my vagrant file in it shows:
```
bundler: failed to load command: vagrant (/usr/local/lib/ruby/gems/2.3.0/bin/vagrant)
Gem::LoadError: vagrant is not part of the bundle. Add it to Gemfile.
  /usr/local/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:336:in `block (2 levels) in replace_gem'
  /usr/local/lib/ruby/gems/2.3.0/bin/vagrant:22:in `<top (required)>'
```

**Comment by devigned** [comment]
@matt-richardson I'd uninstall the plugin then reinstall it, that way it can pull down the changes to the gems.

**Comment by devigned** [comment]
[vagrant-azure-2.0.0.pre2.gem.zip](https://github.com/Azure/vagrant-azure/files/746550/vagrant-azure-2.0.0.pre2.gem.zip)

@matt-richardson, here's a zip of a gem from that PR. Check out: https://www.vagrantup.com/docs/cli/plugin.html#plugin-install. I think this will help.

Just an fyi, but if you wanted to build a new gem, just run `rake build` from the root of the repo.

**Comment by matt-richardson** [comment]
Okay, got past that now.

Oddly, if I dont specify `vm_size`, it seems to default to `small` rather than the `Standard_DS2_v2` that the code implies...

**Comment by devigned** [comment]
@matt-richardson sounds like that might be a setting in your base box.

```ruby
 config.vm.box = 'azure' # <-- that having the vm_size = 'small' in it
```

You can grab an updated box here: https://github.com/devigned/vagrant-azure/raw/6572eaf0aabfe629109102900bd51826fd3f06dd/dummy.box or in the repo ref for this pull request.

**Comment by matt-richardson** [comment]
I dont think it does - I just created one as per the readme in the example_box folder.

Other than that, it looks good for my scenario (winrm/windows etc)

**Comment by devigned** [comment]
Awesome! I'll pull this in and drop a new version of the gem.

**Pull request merged**
